/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.billing;

/**
 *
 * @author hp
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        logo_name = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        l_time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        l_p_detail = new javax.swing.JLabel();
        l_p_id = new javax.swing.JLabel();
        t_p_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_p_name = new javax.swing.JTextField();
        l_rate = new javax.swing.JLabel();
        t_rate = new javax.swing.JTextField();
        l_qty = new javax.swing.JLabel();
        t_qty = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        l_p_name = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        l_total = new javax.swing.JLabel();
        l_paid_amt = new javax.swing.JLabel();
        l_bal_amt = new javax.swing.JLabel();
        t_total = new javax.swing.JTextField();
        t_paid_amt = new javax.swing.JTextField();
        t_bal_amt = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\billing.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 24, 62, -1));

        logo_name.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\Billing ani.gif")); // NOI18N
        getContentPane().add(logo_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 6, -1, -1));

        l_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_date.setText("DATE:");
        getContentPane().add(l_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 18, -1, -1));

        l_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_time.setText("TIME:");
        getContentPane().add(l_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 62, 44, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 18, 37, -1));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 62, 37, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 1148, 10));

        l_p_detail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l_p_detail.setText("PRODUCTS DETAILS");
        getContentPane().add(l_p_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 136, -1, -1));

        l_p_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_p_id.setText("PRODUCT ID");
        getContentPane().add(l_p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 190, -1, -1));

        t_p_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 187, 100, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 186, 37, -1));

        t_p_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 187, 160, -1));

        l_rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_rate.setText("RATE");
        getContentPane().add(l_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        t_rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_rateActionPerformed(evt);
            }
        });
        getContentPane().add(t_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 187, 100, -1));

        l_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_qty.setText("QTY");
        getContentPane().add(l_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 190, 37, -1));

        t_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 187, 71, -1));

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\add.png")); // NOI18N
        add.setText("ADD");
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 186, -1, -1));

        l_p_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_p_name.setText("PRODUCT NAME");
        getContentPane().add(l_p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 126, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, 1160, 10));

        display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QTY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(display_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 565, 287));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("CALCULATION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 267, -1, -1));

        l_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_total.setText("TOTAL");
        getContentPane().add(l_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 355, -1, -1));

        l_paid_amt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_paid_amt.setText("PAID AMOUNT");
        getContentPane().add(l_paid_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 419, -1, -1));

        l_bal_amt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l_bal_amt.setText("BALANCE AMOUNT");
        getContentPane().add(l_bal_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        t_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 352, 150, -1));

        t_paid_amt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_paid_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 416, 150, -1));

        t_bal_amt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t_bal_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 477, 150, -1));

        save.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\save.png")); // NOI18N
        save.setText("SAVE");
        save.setActionCommand("");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 351, 87, -1));

        reset.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\Reset.png")); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 415, -1, -1));

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\close Jframe.png")); // NOI18N
        close.setText("CLOSE");
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 476, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\ICON\\bms\\billing background.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void t_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_rateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private javax.swing.JTable display_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l_bal_amt;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_p_detail;
    private javax.swing.JLabel l_p_id;
    private javax.swing.JLabel l_p_name;
    private javax.swing.JLabel l_paid_amt;
    private javax.swing.JLabel l_qty;
    private javax.swing.JLabel l_rate;
    private javax.swing.JLabel l_time;
    private javax.swing.JLabel l_total;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo_name;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField t_bal_amt;
    private javax.swing.JTextField t_p_id;
    private javax.swing.JTextField t_p_name;
    private javax.swing.JTextField t_paid_amt;
    private javax.swing.JTextField t_qty;
    private javax.swing.JTextField t_rate;
    private javax.swing.JTextField t_total;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
